variable "instance-type" {}
variable "key-name" {}
variable "vpc-id" {}
variable "your-public-IP" {}
variable "access-key" {}
variable "secret-key" {}
variable "region" {}
variable "bucket-name" {}
variable "bucket-path" {}
variable "dynamodb-table-name" {}